In [1]:
import numpy as np

# Array Creation

## Creating arrays from lists

In [7]:
x = np.array([2, 3.5, -1, 50, 0],dtype = np.float32)
x

array([ 2. ,  3.5, -1. , 50. ,  0. ], dtype=float32)

In [9]:
A = np.array([[1, -3, 2],[2, 0, 1]])
A

array([[ 1, -3,  2],
       [ 2,  0,  1]])

In [10]:
A.shape

(2, 3)

In [13]:
lst_sq = [i**2 for i in range(5)]

In [16]:
lst_sq_mod = list()
for i in range(5):    
    lst_sq_mod.append(i**2)
lst_sq_mod


[0, 1, 4, 9, 16]

In [14]:
x = np.array(lst_sq)
x

array([ 0,  1,  4,  9, 16])

## How to specify the type of array elements.

In [18]:
x = np.array([1.2, 3.4, -2.0], dtype=np.float32)
x

array([ 1.2,  3.4, -2. ], dtype=float32)

## Creating an empty array with a given shape

In [22]:
x = np.empty((3,2))
x

array([[4.68473578e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [20]:
x = np.empty((2,4), dtype=np.int16)
x

array([[    0, 16384,     0, 16480],
       [    0, 16256,     0, 16968]], dtype=int16)

In [26]:
%%timeit
x = np.empty((2,3))
x

238 ns ± 0.627 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## How to create an array with zeros, ones and with a single value

In [23]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
%%timeit
x = np.zeros((2,3))
x

254 ns ± 2.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
x = np.ones(shape = (4,4),dtype= np.int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
x = np.full(shape = (3,1),fill_value= 3.5)
x

array([[3.5],
       [3.5],
       [3.5]])

## Creating an array with equally spaced elements

In [34]:
x = np.arange(1.1, 1.9, 0.2)
x

array([1.1, 1.3, 1.5, 1.7])

In [35]:
x = np.arange(2.5, 6.5)
x

array([2.5, 3.5, 4.5, 5.5])

In [36]:
x = np.arange(3.5)
x

array([0., 1., 2., 3.])

In [37]:
x = np.arange(0.9, 4.9, dtype=np.int64)
x

array([0, 1, 2, 3])

In [38]:
x = np.arange(0, 4)
x

array([0, 1, 2, 3])

In [40]:
x = np.linspace(1.2, 3.2, 5)
x

array([1.2, 1.7, 2.2, 2.7, 3.2])

## Creating arrays with repeated elements

In [41]:
x = np.repeat(1.2, 3)
x

array([1.2, 1.2, 1.2])

In [42]:
x = np.array([[1,2,3],[4,5,6]])
y = np.repeat(x, 2)
y

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [45]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
y = np.repeat(x, 2, axis=0)
y

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [44]:
y = np.repeat(x, 2, axis=1)
y

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6]])

In [55]:
y = np.repeat(x, [2, 3], axis=0)
y

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [56]:
y = np.repeat(x, [2, 1], axis=0)
y

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.repeat(x, [1,0,1,0], axis=1)
y

array([[1, 3],
       [5, 7]])

## Creating an array by tiling another array

In [60]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [63]:
y = np.tile(x,(3,3))
y

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

## Querying and changing the shape of an array

In [64]:
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x.shape

(2, 6)

In [ ]:
x.shape

In [68]:
x.shape = (4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
x.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [74]:
_ + 1

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

## Creating arrays with the same shape as another array

In [75]:
x = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
y = np.zeros_like(x)
y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
np.zeros(x.shape)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
y = np.zeros(x.shape)
y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
x = np.array([[1,1],[2,2]])
z = np.full_like(x, 6.2)
z

array([[6, 6],
       [6, 6]])

In [80]:
z = np.full_like(x, 6.2, dtype=np.float64)
z

array([[6.2, 6.2],
       [6.2, 6.2]])

## How to join arrays

In [81]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
w = np.column_stack([x,y,z])
w

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
c = np.row_stack([x,y,z])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60],[70,80,90]])
z = np.concatenate([x,y])
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [84]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
y = np.array([[10,20],[30,40]])
z = np.concatenate([x,y], axis=1)
z

array([[ 1,  2,  3,  4, 10, 20],
       [ 5,  6,  7,  8, 30, 40]])

In [85]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60],[70,80,90]])
z = np.vstack([x,y])
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [86]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
y = np.array([[10,20],[30,40]])
z = np.hstack([x,y])
z

array([[ 1,  2,  3,  4, 10, 20],
       [ 5,  6,  7,  8, 30, 40]])

In [87]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9]])
z = np.append(x, y , axis=0)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[10],[20],[30]])
z = np.append(x, y, axis=1)
z

array([[ 1,  2, 10],
       [ 3,  4, 20],
       [ 5,  6, 30]])

# Storage and retrieval of NumPy arrays

## How to store an array using text format

In [27]:
x = np.random.rand(200, 300)
x

array([[0.3700303 , 0.65366409, 0.22805646, ..., 0.00580112, 0.60068584,
        0.77889866],
       [0.8221824 , 0.23406045, 0.13098015, ..., 0.9395603 , 0.87167739,
        0.60612137],
       [0.24065993, 0.80017507, 0.57261672, ..., 0.2061532 , 0.3890097 ,
        0.62635773],
       ...,
       [0.73187064, 0.90538022, 0.31177969, ..., 0.99704331, 0.54725199,
        0.63999654],
       [0.61738264, 0.41135664, 0.35063576, ..., 0.25200247, 0.55626841,
        0.73474948],
       [0.87283118, 0.67284238, 0.25920739, ..., 0.98986775, 0.8747187 ,
        0.85668942]])

In [28]:
np.savetxt('array_x.txt', x)

In [ ]:
m, n = 10, 5
x = np.random.rand(m, n)
columns = ','.join(['Column {}'.format(str(i+1)) for i in range(n)])
np.savetxt('array_x.csv', x, fmt='%10.8f', 
           delimiter=',', header=columns, comments='')

## How to load an stored in text format

In [29]:
x = np.loadtxt('array_x.txt')
x

array([[0.3700303 , 0.65366409, 0.22805646, ..., 0.00580112, 0.60068584,
        0.77889866],
       [0.8221824 , 0.23406045, 0.13098015, ..., 0.9395603 , 0.87167739,
        0.60612137],
       [0.24065993, 0.80017507, 0.57261672, ..., 0.2061532 , 0.3890097 ,
        0.62635773],
       ...,
       [0.73187064, 0.90538022, 0.31177969, ..., 0.99704331, 0.54725199,
        0.63999654],
       [0.61738264, 0.41135664, 0.35063576, ..., 0.25200247, 0.55626841,
        0.73474948],
       [0.87283118, 0.67284238, 0.25920739, ..., 0.98986775, 0.8747187 ,
        0.85668942]])

In [ ]:
x[0:3, 0:3]

In [30]:
x = np.loadtxt('employees.txt', delimiter=',',
               skiprows=1, usecols=(1,3,4))

In [31]:
x

array([[1.01e+02, 4.20e+04, 5.00e+00],
       [2.03e+02, 3.10e+04, 3.00e+00],
       [1.05e+02, 6.70e+04, 8.00e+00]])

In [32]:
import pandas as pd

In [40]:
pd.read_csv('employees.txt')['ID'].values.dtype

dtype('int64')

In [36]:
pd.read_csv('array_x.csv').values

array([[0.67133, 0.19562, 0.25712, 0.27632, 0.40951],
       [0.74356, 0.9263 , 0.84511, 0.60594, 0.84618],
       [0.20117, 0.68052, 0.49081, 0.6406 , 0.17048],
       [0.47305, 0.83454, 0.7571 , 0.29675, 0.27116],
       [0.065  , 0.9954 , 0.25106, 0.20131, 0.89415],
       [0.16831, 0.583  , 0.46791, 0.14735, 0.35021],
       [0.24832, 0.28138, 0.37673, 0.84313, 0.82642],
       [0.47623, 0.61546, 0.2473 , 0.86174, 0.77931],
       [0.24858, 0.00588, 0.71372, 0.97082, 0.56631],
       [0.87172, 0.79439, 0.87754, 0.10092, 0.05879]])

## How to store a single array in binary format

In [ ]:
x = np.random.rand(200, 300)
np.save('array_x.npy', x)

In [ ]:
x[:3,:3]

# Indexing

In [89]:
m = n = 10
x = np.array([np.arange(n) + m*i for i in range(n)])

In [90]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
y = x[2:4,[2,4,-1]]
y

array([[22, 24, 29],
       [32, 34, 39]])

In [ ]:
y = x[1:5:2, 2:10:3]
y

In [ ]:
y = x[4:1:-1, 2]
y

In [ ]:
y = x[:, 5]
y

In [ ]:
y = x[[2, 3, 1], [0, 3, 5]]
y

In [ ]:
y = x[:, [5, 2, -1]]
y

||,& instead or,and

In [97]:
condition = x > 87
condition

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [98]:
y = x[condition]
y

array([88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [99]:
x = np.array([[-1, 2, 4], [2, -3, 1], [2, 4, 0], 
              [-5, 4, 3], [3, 1, 1], [2, 0, -4]])
x

array([[-1,  2,  4],
       [ 2, -3,  1],
       [ 2,  4,  0],
       [-5,  4,  3],
       [ 3,  1,  1],
       [ 2,  0, -4]])

In [102]:
row_sums = x.sum(axis=1)
row_sums

array([ 5,  0,  6,  2,  5, -2])

In [103]:
y = x[row_sums % 2 == 0, :]
y

array([[ 2, -3,  1],
       [ 2,  4,  0],
       [-5,  4,  3],
       [ 2,  0, -4]])

In [ ]:
x

In [ ]:
x.sum(axis=1)

In [104]:
mask = np.sum(x, axis=1) % 2 == 0
mask

array([False,  True,  True,  True, False,  True])

In [106]:
x[mask, :]

array([[ 2, -3,  1],
       [ 2,  4,  0],
       [-5,  4,  3],
       [ 2,  0, -4]])

## Operations on arrays

In [6]:
x = np.pi * np.arange(0, 2, 0.25)
y = np.sin(x)
y

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01])

In [7]:
x = np.array([1.2, -0.23, 3.4])
y = np.array([2.4, -1.7, -5.4])
z = x + y
z

array([ 3.6 , -1.93, -2.  ])

### Broadcasting

In [8]:
x=np.array([1,2,3])
z = 2 * x
z

array([2, 4, 6])

<html>
<img alt="Vector-Scalar multiplication" src="theory.broadcast_1.gif">
</html>

In [9]:
a = np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
b = np.array([1,2,3])
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<img alt="Matrix-Vector" src="theory.broadcast_2.gif">

In [10]:
b= np.array([1,2,3,4])
a+b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

<img alt="Matrix-Vector-with-error" src="theory.broadcast_3.gif">

## Computing the matrix product of two arrays

In [11]:
A = np.array([[2.3, 4.5, -3.1],
              [1.2, 3.2,  4.0]])
B = np.array([[ 2.1, -4.6, 0.5, 2.2],
              [-1.2, -3.0, 1.7, 3.2],
              [ 3.1,  2.6, 1.1, 2.3]])
C = A.dot(B)
C

array([[-10.18, -32.14,   5.39,  12.33],
       [ 11.08,  -4.72,  10.44,  22.08]])

In [12]:
u = np.array([0.5, 2.3, -4.0])
v = np.array([3.2, -5.4])
w = A.dot(u)
z = v.dot(A)

In [13]:
w

array([23.9 , -8.04])

In [14]:
z

array([  0.88,  -2.88, -31.52])

# Object arrays

In [15]:
x = np.array([2.5, 'a string', [2,4], {'a':0, 'b':1}, np.array([2,3])])

In [16]:
x

array([2.5, 'a string', list([2, 4]), {'a': 0, 'b': 1}, array([2, 3])],
      dtype=object)

In [22]:
type(x),x.dtype

(numpy.ndarray, dtype('O'))

In [23]:
[type(item) for item in x]

[float, str, list, dict, numpy.ndarray]

In [24]:
x = np.empty((2,2), dtype=np.object)
x

array([[None, None],
       [None, None]], dtype=object)